# Generated by Django 3.1.1 on 2020-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Roll_no', models.CharField(max_length=20)),
                ('Branch', models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('it', 'IT'), ('mech', 'MECH')], max_length=5)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(help_text='Enter 10 digit mobile number', max_length=10)),
            ],
        ),
    ]
