# Generated by Django 3.1.1 on 2020-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200924_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Department', models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('it', 'IT'), ('mech', 'MECH'), ('chem', 'CHEM')], max_length=10)),
                ('Publication_date', models.DateField()),
            ],
        ),
    ]
